controller_manager_ns: controller_manager
controller_list:
 - name: arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - shoulder_yaw_joint_rev
      - shoulder_pitch_joint_rev
      - elbow
      - wrist_pitch
      - wrist_yaw
      - wrist_roll