<?xml version ="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mobile_manipulator">

<material name="white">
  <color rgba="1 1 1 1"/>
</material>  

<xacro:property name="MXLength" value="0.0611"/>
<xacro:property name="MXWidth" value="0.041"/>
<xacro:property name="MXDepth" value="0.0402"/>

<xacro:property name="AXLength" value="0.05"/>
<xacro:property name="AXWidth" value="0.032"/>
<xacro:property name="AXDepth" value="0.04"/>

<xacro:property name="length" value="0.096"/>

<xacro:macro name="MXInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="MXVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/dynamixel_x64series.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="MXCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <box size="0.041 0.0402 0.0611"/>
      </geometry>    
    </collision> 
</xacro:macro>  

<xacro:macro name="AXInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="0.05573" />
    <inertia ixx="0.00001611154" ixy="0.00000001397" ixz="0.0" iyy="0.00000888743" iyz="0.00000015948" izz="0.00001354172" />
  </inertial>
</xacro:macro>

<xacro:macro name="AXVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/AX-12_18A - dynamixel_AXseries-1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="AXCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <box size="0.032 0.04 0.05"/>
      </geometry>    
    </collision> 
</xacro:macro>

<xacro:macro name="BracketInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="0.00712" />
    <inertia ixx="0.00000174511" iyy="0.00000379922" ixz="0.0" ixy="0.0" iyz="0.0" izz="0.00000357521" />
  </inertial>
</xacro:macro>

<xacro:macro name="BracketVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/FR05-H101K.stl" scale="0.001 0.001 0.001" />
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="BracketCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/FR05-H101K.stl" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>  

<xacro:macro name="AxBracketInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="0.00712" />
    <inertia ixx="0.00000174511" iyy="0.00000379922" ixz="0.0" ixy="0.0" iyz="0.0" izz="0.00000357521" />
  </inertial>
</xacro:macro>

<xacro:macro name="AxBracketVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/F4.stl" scale="0.001 0.001 0.001" />
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="AxBracketCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/F4.stl" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>  

<xacro:macro name="LinkInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="${0.005*length}" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394"/>
  </inertial>
</xacro:macro>

<xacro:macro name="LinkVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <box size="0.04 0.04 ${length}"/>
    </geometry>
    <material name="white"/>       
  </visual>
</xacro:macro>

<xacro:macro name="LinkCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <box size="0.04 0.04 ${length}"/>
      </geometry>    
    </collision> 
</xacro:macro> 

<xacro:macro name="Revjoint" params="id trans rpy parent child axis l u v">
    <joint name="${id}" type="revolute">
      <origin xyz="${trans}" rpy="${rpy}"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${axis}"/>
      <limit lower="${l}" upper="${u}" effort="30" velocity="${v}"/>
    </joint>
</xacro:macro> 

<xacro:macro name="FxdJoint" params="id parent child">
    <joint name="${id}" type="fixed">
      <parent link="${parent}"/>
      <child link="${child}"/>
    </joint>
</xacro:macro>        




  <link name="base_link">
    <xacro:MXInertial trans="0 0 0" rpy="0 0 0 "/>  
    <xacro:MXVisual trans="0 0 0" rpy="0 0 0 "/>
    <xacro:MXCollision trans="0 0 0" rpy="0 0 0"/>
  </link>

  <link name="link1Bracket">
    <xacro:BracketInertial trans="0 0 0.025" rpy="0 3.14 0 "/>
    <xacro:BracketVisual trans="0 0 0.025" rpy="0 3.14 0 "/>
    <xacro:BracketCollision trans="0 0 0.025" rpy="0 3.14 0 "/>
  </link>  

  <link name="shoulder1">
    <xacro:MXInertial trans="0 0 0" rpy="1.57 -3.14 1.57"/>  
    <xacro:MXVisual trans="0 0 0" rpy="1.57 -3.14 1.57"/>
    <xacro:MXCollision trans="0 0 0" rpy="1.57 -3.14 1.57"/>
  </link>

  <link name="link2">
    <xacro:LinkInertial trans="0 0 ${0.0481+(length/2)}" rpy="0 0 0" />
    <xacro:LinkVisual trans="0 0 ${0.0481+(length/2)}" rpy="0 0 0" />
    <xacro:LinkCollision trans="0 0 ${0.0481+(length/2)}" rpy="0 0 0" />
  </link> 

  <link name="link2Bracket">
    <xacro:BracketInertial trans="0 0 ${0.0481+length}" rpy="0 3.14 0"/>
    <xacro:BracketVisual trans="0 0 ${0.0481+length}" rpy="0 3.14 0"/>
    <xacro:BracketCollision trans="0 0 ${0.0481+length}" rpy="0 3.14 0"/>
  </link>   

  <link name="elbow">
    <xacro:MXInertial trans="0 0 0" rpy="1.57 0 0"/>  
    <xacro:MXVisual trans="0 0 0" rpy="1.57 3.14 -1.57"/>
    <xacro:MXCollision trans="0 0 0" rpy="1.57 0 0"/>
  </link>

  <link name="link3">
    <xacro:LinkInertial trans="0 0 ${0.0481+(length/2)}" rpy="0 0 0" />
    <xacro:LinkVisual trans="0 0 ${0.0481+(length/2)}" rpy="0 0 0" />
    <xacro:LinkCollision trans="0 0 ${0.0481+(length/2)}" rpy="0 0 0" />
  </link> 
  
  <link name="link3Bracket">
    <xacro:AxBracketInertial trans="0 0 ${0.0988+length}" rpy="1.57 0 1.57"/>
    <xacro:AxBracketVisual trans="0 0 ${0.0988+length}" rpy="1.57 0 1.57"/>
    <xacro:AxBracketCollision trans="0 0 ${0.0988+length}" rpy="1.57 0 1.57"/>
  </link>

  <link name="WristPitch">
    <xacro:AXInertial trans="0 0 0" rpy="-1.57 0 -1.57"/>
    <xacro:AXVisual trans="0. 0 0" rpy="-1.57 0 -1.57"/>
    <xacro:AXCollision trans="0 0 0" rpy="-1.57 0 -1.57"/>
  </link>     

  <link name="WristRoll">
    <xacro:AXInertial trans="0 0.015 0.0585" rpy="0 0 0"/>
    <xacro:AXVisual trans="0 0.015 0.0585" rpy="0 0 0"/>
    <xacro:AXCollision trans="0 0.015 0.0585" rpy="0 0 0"/>
  </link> 

 <link name="end_effector">
    <xacro:BracketInertial trans="0 0 0" rpy="3.14 0 1.57"/>
    <xacro:BracketVisual trans="0 0 0" rpy="3.14 0 -1.57"/>
    <xacro:BracketCollision trans="0 0 0" rpy="3.14 0 1.57"/>
  </link>

  
  
 
  <xacro:Revjoint id="one" trans="0 0 0" rpy="0 0 0" parent="base_link" child="link1Bracket" axis="0 0 1" l="-3.14" u="3.14" v="1.0"/>
  <xacro:Revjoint id="two" trans="0 0 0.0636" rpy="0 0 0" parent="link1Bracket" child="shoulder1" axis="1 0 0" l="-1.57" u="1.57" v="1.0"/>
  <xacro:FxdJoint id="s1_l2" parent="shoulder1" child="link2"/>
  <xacro:FxdJoint id="l2_l2B" parent="link2" child="link2Bracket"/>
  <xacro:Revjoint id="three" trans="0 0 ${0.0867+(length)}" rpy="0 0 0" parent="link2Bracket" child="elbow" axis="1 0 0" l="-1.57" u="1.57" v="1.0"/>
  <xacro:FxdJoint id="e_l3" parent="elbow" child="link3"/>
  <xacro:FxdJoint id="l3_l3B" parent="link3" child="link3Bracket"/>
  <xacro:Revjoint id="four" trans="0 0 ${0.0988+length}" rpy="0 0 0" parent="link3Bracket" child="WristPitch" axis="1 0 0" l="-1.57" u="1.57" v="1.0"/>
  <xacro:FxdJoint id="WP_WR" parent="WristPitch" child="WristRoll"/>
  <xacro:Revjoint id="five" trans="0 0.015 0.0785" rpy="0 0 0" parent="WristRoll" child="end_effector" axis="0 0 1" l="-3.14" u="3.14" v="1.0"/>

</robot>